#!/usr/bin/env bash
# install nginx web server
sudo apt-get update
sudo apt-get install nginx -y
sudo mkdir -p /var/www/html
sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www
echo "Holberton School" > /var/www/html/index.html
