#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to other page
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
sed -i 's/server_name _;/server_name _;\nrewrite ^\/redirect_me andresito.tech permanent;/' /etc/nginx/sites-available/default
service nginx start
