#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to other page
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/error.html
sed -i '18 a rewrite ^\/redirect_me https://twitter.com/ariza_rocks/photo permanent;' /etc/nginx/sites-enabled/default
sed -i '19 a error_page 404 /error.html;' /etc/nginx/sites-enabled/default
service nginx restart
