#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to other page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Holberton School" > /var/www/html/index.html
sudo echo "Ceci n'est pas une page" > /var/www/html/error.html
sudo sed -i '18 a \\trewrite ^\/redirect_me https://twitter.com/ariza_rocks/photo permanent;' /etc/nginx/sites-enabled/default
sudo sed -i '19 a \\terror_page 404 /error.html;' /etc/nginx/sites-enabled/default
sudo service nginx start
