#!/usr/bin/env bash
# displays To ifinity and beyond indefinitely
echo $$ > /var/run/holbertonscript.pid
trap nomore QUIT
trap "echo Y U no love me?!" INT
trap elephant TERM
elephant()
{
    echo "I hate the kill command"
    rm -rf /var/run/holbertonscript.pid
    exit 0
}
nomore()
{
    rm -rf /var/run/holbertonscript.pid
    exit 0
}
while :
do
    echo To infinity and beyond
    sleep 2
done
