#!/usr/bin/env bash
# Displays the content of the file /etc/passwd
n=0
while IFS=: read -r f1 f2 f3 _ f5 f6 f7
do
    echo "The user $f1 is part of the $f3 gang, lives in $f6 and rides $f7. $n's place is protected by the passcode $f2, more info about the user here: $f5"
    n=$((n+1))
done < "/etc/passwd"
